# Cleaning Script

library(dplyr)

data <- readr::read_csv("Brazilian Zouk Survey - 2022.csv")

# Rename
data_names <- c("q1","q2", "age",
                "role", "exp_years", "exp_level",
                "location",
                "gc_class_freq",
                "gc_type",
                "gc_hours",
                "gc_price",
                "gc_learning_style",
                "gc_structure",
                "gc_topics",
                "gc_barrier",
                "gc_length",
                "gc_prog_drop",
                "gc_practica",
                "gc_practica_price",
                "instructor_events",
                "private_lesson",
                "private_offer",
                "private_type",
                "private_goals",
                "private_freq",
                "private_where",
                "private_barrier",
                "socials",
                "social_invite",
                "social_give_correction",
                "social_get_correction",
                "social_start",
                "social_start_ideal",
                "social_arrive",
                "social_depart",
                "social_songs",
                "social_dj_price",
                "events",
                "event_type",
                "event_social_freq",
                "event_social_price",
                "event_weekshop_freq",
                "event_weekshop_price",
                "event_congress",
                "event_congress_price",
                "competition_interest",
                "competition_interest_change",
                "r_location",
                "r_parking",
                "r_floors",
                "r_ambiance",
                "r_amenities",
                "r_music",
                "r_size",
                "r_artists",
                "r_workshops",
                "r_time",
                "event_max_classes",
                "event_comf_classes",
                "challenge",
                "fear",
                "rewarding",
                "retention",
                "s_musicality",
                "s_physical",
                "s_close_position",
                "s_spiritual",
                "s_boundaries",
                "s_respect",
                "s_sex",
                "s_romantic",
                "s_explore",
                "c_forehead",
                "c_cheek",
                "c_chin",
                "c_neck",
                "c_shoulder",
                "c_arm",
                "c_hand",
                "c_chest",
                "c_upper_back",
                "c_lower_back",
                "c_hips",
                "c_upper_thigh",
                "c_knee",
                "c_lower_leg",
                "c_foot",
                "music_style",
                "accessibility",
                "more_accessibility",
                "wyr_location",
                "wyr_headline_floor",
                "wyr_lighting",
                "wyr_class_social",
                "wyr_pattern_concept",
                "wyr_session_type",
                "comments")
# Rename columns and drop unneeded columns
colnames(data) <- data_names
data <- data %>% 
  dplyr::select(-c("q1","q2"))

# Formating column types
data2 <- data %>%
  mutate(age = as.numeric(gsub("([0-9]+).*$", "\\1", age)),
         role = factor(role),
         exp_years = as.numeric(dplyr::case_when(exp_years == "Less than a year." ~ "1", 
                                      exp_years == ".4" ~ ".4",
                                      TRUE ~ stringr::str_extract(exp_years, "\\d+\\.*\\d*"))),
         exp_level = factor(exp_level, levels = c("Novice",
                                                  "Beginner", 
                                                  "Intermediate",
                                                  "Advanced",
                                                  "Professional/All Star")),
         location = dplyr::case_when(stringr::str_detect(location, "USA") ~ "USA",
                                     stringr::str_detect(location, "United States") ~ "USA",
                                     stringr::str_detect(location, "DC") ~ "USA",
                                     stringr::str_detect(location, "Michigan") ~ "USA",
                                     stringr::str_detect(location, "Washington") ~ "USA",
                                     stringr::str_detect(location, "FL") ~ "USA",
                                     stringr::str_detect(location, "Georgia") ~ "USA",
                                     stringr::str_detect(location, "MO") ~ "USA",
                                     stringr::str_detect(location, "Texas") ~ "USA",
                                     stringr::str_detect(location, "California") ~ "USA",
                                     stringr::str_detect(location, "Australia") ~ "Australia",
                                     stringr::str_detect(location, "Texas") ~ "USA",
                                     stringr::str_detect(location, "Canada") ~ "Canada",
                                     stringr::str_detect(location, "Quebec") ~ "Canada",
                                     stringr::str_detect(location, "UK") ~ "Europe",
                                     stringr::str_detect(location, "London") ~ "Europe",
                                     stringr::str_detect(location, "England") ~ "Europe",
                                     location=="Poland" ~ "Europe",
                                     location=="Denmark" ~ "Europe",
                                     location=="Germany" ~ "Europe",
                                     location=="Ireland" ~ "Europe",
                                     location=="Netherlands" ~ "Europe",
                                     location=="Switzerland" ~ "Europe",
                                     location=="Romania" ~ "Europe",
                                     location=="Hong Kong" ~ "Asia",
                                     location=="Indonesia" ~ "Asia",
                                     location=="Japan" ~ "Asia",
                                     location=="Singapore" ~ "Asia",
                                     TRUE ~ location),
         gc_class_freq = factor(gc_class_freq, levels = c("Never, or less than once a month",
                                                          "Once a month",
                                                          "2-3 times a month",
                                                          "Once a week",
                                                          "Multiple times a week")),
         gc_type = factor(gc_type, levels = c("In Person", "Online", "Mixed")),
         gc_hours = as.numeric(dplyr::case_when(gc_hours == ".5" ~ ".5",
                               TRUE ~ stringr::str_extract(gc_hours, "\\d+\\.*\\d*")))
  )
           
  
